#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__ . '/bootstrap/app.php';
app($app);

exit((new \Nova\Console\Console($app))->run($_SERVER['argv'] ?? []));
