<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/admin/reports/layout.latte */
final class Template_33cec31122 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="reports-layout" data-layout="reports">
    <header>Reports</header>
    ';
		echo $content /* pos 3:5 */;
		echo '
</section>
';
	}
}
