<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/dashboard/page.latte */
final class Template_3b5a02ee21 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="dashboard-page">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
';
		echo $this->global->componentEngine->renderFromArguments(['StatsCard', 'label' => 'Revenue', 'value' => $revenue]) /* pos 3:5 */;
		echo $this->global->componentEngine->renderFromArguments(['Card', 'title' => 'Nested Component', 'body' => 'This card renders a Button, and Button renders Icon.']) /* pos 4:5 */;
		echo '</section>
';
	}
}
