<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/users/page.latte */
final class Template_9c22466780 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<form action="/users/actions/save" method="POST">
    ';
		echo csrf_field() /* pos 2:5 */;
		echo '
    <label>
        Name
        <input name="name"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->global->fn->old)($this, 'name')) /* pos 5:36 */;
		echo ' required>
    </label>
    <button type="submit">Save</button>
</form>

<ul class="users-list">
';
		foreach ($users as $user) /* pos 11:5 */ {
			echo '        <li><a href="/users/';
			echo LR\HtmlHelpers::escapeAttr($user['id']) /* pos 12:29 */;
			echo '">';
			echo LR\HtmlHelpers::escapeText($user['name']) /* pos 12:44 */;
			echo '</a></li>
';

		}

		echo '</ul>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['user' => '11'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
