<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/login/page.latte */
final class Template_dc2007d625 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 1:5 */;
		echo '</h1>
';
	}
}
