<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/layout.latte */
final class Template_290ce34d2a extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token"';
		echo LR\HtmlHelpers::formatAttribute(' content', csrf()) /* pos 6:39 */;
		echo '>
    <title>';
		echo LR\HtmlHelpers::escapeText(($this->filters->default)($title, 'Nova')) /* pos 7:12 */;
		echo '</title>
';
		echo $this->global->asset->tags('app.scss') /* pos 8:5 */;
		echo '</head>
<body>
    <main class="nova-shell">
        ';
		echo $content /* pos 12:9 */;
		echo '
    </main>
    <script>
        window.Nova = Object.assign(window.Nova || {}, {
            env: ';
		echo LR\HtmlHelpers::convertJSToRawText(json_encode(config('app.env', 'production'))) /* pos 16:18 */;
		echo ',
            ui: ';
		echo LR\HtmlHelpers::convertJSToRawText(json_encode(config('ui', []))) /* pos 17:17 */;
		echo '
        });
    </script>
';
		echo $this->global->asset->tags('app.ts') /* pos 20:5 */;
		echo '</body>
</html>
';
	}
}
