<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/about/page.latte */
final class Template_98ada7f683 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="nova-page nova-page-about">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>';
		echo LR\HtmlHelpers::escapeText($message) /* pos 3:8 */;
		echo '</p>
    <a href="/">Back home</a>
</section>
';
	}
}
