<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/page.latte */
final class Template_3784408c60 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="nova-page nova-page-home">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>';
		echo LR\HtmlHelpers::escapeText($message) /* pos 3:8 */;
		echo '</p>
    <nav>
        <a href="/about">About</a>
        <a href="/users">Users</a>
        <a href="/users/15">User 15</a>
    </nav>
</section>
';
	}
}
