<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/users/layout.latte */
final class Template_a02b3f2950 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="users-layout">
    <header>
        <h2>Users</h2>
    </header>
    ';
		echo $content /* pos 5:5 */;
		echo '
</section>
';
	}
}
