<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: components/Icon/component.latte */
final class Template_3a5b28a46e extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<span class="nova-icon" aria-hidden="true">';
		echo LR\HtmlHelpers::escapeText($name) /* pos 1:44 */;
		echo '</span>
';
	}
}
