<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/dashboard/components/StatsCard/component.latte */
final class Template_a408cf02b8 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<article class="stats-card stats-card-dashboard" data-component-scope="dashboard">
    <span>';
		echo LR\HtmlHelpers::escapeText($label) /* pos 2:11 */;
		echo '</span>
    <strong>';
		echo LR\HtmlHelpers::escapeText($value) /* pos 3:13 */;
		echo '</strong>
</article>
';
	}
}
