<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: components/Card/component.latte */
final class Template_e477001541 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<article class="nova-card">
    <h3>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h3>
    <p>';
		echo LR\HtmlHelpers::escapeText($body) /* pos 3:8 */;
		echo '</p>
';
		echo $this->global->componentEngine->renderFromArguments(['Button', 'text' => 'Open', 'color' => 'secondary', 'icon' => 'go']) /* pos 4:5 */;
		echo '</article>
';
	}
}
