<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: components/Button/component.latte */
final class Template_fc1bf95957 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<button class="nova-button nova-button-';
		echo LR\HtmlHelpers::escapeAttr($color) /* pos 1:40 */;
		echo '"';
		echo LR\HtmlHelpers::formatAttribute(' type', $type) /* pos 1:57 */;
		echo '>
';
		echo $this->global->componentEngine->renderFromArguments(['Icon', 'name' => $icon]) /* pos 2:5 */;
		echo '    <span>';
		echo LR\HtmlHelpers::escapeText($text) /* pos 3:11 */;
		echo '</span>
</button>
';
	}
}
