<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/users/[id]/orders/page.latte */
final class Template_54057c0342 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="orders-page">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>User ID: ';
		echo LR\HtmlHelpers::escapeText($userId) /* pos 3:17 */;
		echo '</p>
</section>
';
	}
}
