<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/docs/[...slug]/page.latte */
final class Template_66dc5f7c82 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="docs-page">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>Slug: ';
		echo LR\HtmlHelpers::escapeText(implode('/', $slug)) /* pos 3:14 */;
		echo '</p>
</section>
';
	}
}
