<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/users/[id]/page.latte */
final class Template_19ce2a89f1 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<article class="user-detail">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>Route parameter: ';
		echo LR\HtmlHelpers::escapeText($userId) /* pos 3:25 */;
		echo '</p>
    <a href="/users">Back to users</a>
</article>
';
	}
}
