<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/blog/[[...slug]]/page.latte */
final class Template_4a2286d2a3 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="blog-page">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>Slug: ';
		if ($slug) /* pos 3:14 */ {
			echo LR\HtmlHelpers::escapeText(implode('/', $slug)) /* pos 3:24 */;
		} else /* pos 3:45 */ {
			echo 'index';
		}
		echo '</p>
</section>
';
	}
}
