<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/products/[category]/[product]/page.latte */
final class Template_8416244474 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="product-page">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>Category: ';
		echo LR\HtmlHelpers::escapeText($category) /* pos 3:18 */;
		echo '</p>
    <p>Product: ';
		echo LR\HtmlHelpers::escapeText($product) /* pos 4:17 */;
		echo '</p>
</section>
';
	}
}
