<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: app/admin/reports/sales/page.latte */
final class Template_094342bbde extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<article class="sales-report" data-page="sales">
    <h1>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 2:9 */;
		echo '</h1>
    <p>';
		echo LR\HtmlHelpers::escapeText($message) /* pos 3:8 */;
		echo '</p>
</article>
';
	}
}
