<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: resources/views/welcome.latte */
final class Template_7815ef65f1 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		echo '<section class="nova-welcome">
    <h1>Hello Nova</h1>
    <p>Latte, Vite, TypeScript, and SCSS are ready.</p>
</section>
';
	}
}
