<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: resources/errors/500.latte */
final class Template_97f37a428d extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>500 - Server Error</title>
</head>
<body>
    <h1>500</h1>
    <p>';
		echo LR\HtmlHelpers::escapeText($message) /* pos 10:8 */;
		echo '</p>
</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = false;
		return get_defined_vars();
	}
}
