<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: tests/fixtures/validation.latte */
final class Template_7af6eb8da5 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<p>';
		echo LR\HtmlHelpers::escapeText((($this->global->fn->errors)($this, ))->first('email')) /* pos 1:4 */;
		echo '</p>
<p>';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->old)($this, 'email')) /* pos 2:4 */;
		echo '</p>
<p>';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->session)($this, 'notice')) /* pos 3:4 */;
		echo '</p>
';
	}
}
